# Generated by Django 2.1.2 on 2019-04-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_num', models.IntegerField()),
                ('item_type', models.CharField(max_length=50, null=True)),
                ('item_title', models.CharField(max_length=50)),
                ('item_a_anwser', models.CharField(max_length=50)),
                ('item_b_anwser', models.CharField(max_length=50)),
                ('item_c_anwser', models.CharField(max_length=50)),
                ('one_score_anwser', models.CharField(max_length=50, null=True)),
                ('tow_score_anwser', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
